name: JavaModernization/sonarqube_custom_agent

on:
  workflow_dispatch:
    inputs:
      buildProfile:
        default: default
        type: string
        required: false

env:
  sonarQubeUrl: https://sonarqube-hub.azurewebsites.net
  JAVA_VERSION: '17'

jobs:
  SonarQube-Scan:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean verify -DskipTests

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=Refactoring-legacy-Pharmacy-uc2
            -Dsonar.projectName=Refactoring-legacy-Pharmacy-uc2
            -Dsonar.host.url=${{ env.sonarQubeUrl }}
            -Dsonar.login=${{ secrets.sonarQubeToken }}
            -Dsonar.java.source=${{ env.JAVA_VERSION }}
            -Dsonar.java.binaries=**/target/classes
            -Dsonar.exclusions=documentation/*,.vscode/*,**/target/**
            -Dsonar.newCode.referenceBranch=main